spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/smartcityfix
spring.datasource.username=postgres
spring.datasource.password=Aman@#110504

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true